// Rulings --------------------------------------------------------------------------
export enum RULINGS {
    FETCH_RULING_LIST = 'FETCH_RULING_LIST',
    PUT_RULING_LIST = 'PUT_RULING_LIST',
    PUT_OPTION_RULING_LIST = 'PUT_OPTION_RULING_LIST',
    FETCH_RULING_DETAILS = 'FETCH_RULING_DETAILS',
    PUT_RULING_DETAILS = 'PUT_RULING_DETAILS',
    FETCH_RULING_OPERATION = 'FETCH_RULING_OPERATION',
    PUT_RULING_OPERATION= 'PUT_RULING_OPERATION'
}