import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { AppProps } from 'next/app';
import { Inter } from 'next/font/google';
import '@/globals.css';
import Template from '../components/Template';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <Template>
      <Component {...pageProps} />
    </Template>
  );
};

App.getLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
};

export default App;
